"""empty message

Revision ID: b3f8731b5c66
Revises: deee8f0ed433
Create Date: 2024-03-04 16:41:31.322244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f8731b5c66'
down_revision = 'deee8f0ed433'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thread_title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('thread_content', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.drop_column('thread_content')
        batch_op.drop_column('thread_title')

    # ### end Alembic commands ###
